# Generated by Django 4.2.6 on 2024-07-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_primary_text_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primary_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
